### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tiennou**
Sorry for the dull name.

This is the result of a few years worth of ~love~ low-level work on GitX innards. I'm now running that branch for the time being (I'll likely find bugs and squash them).

The plan is :
- make sure it's not more buggy than it was (heh)
- merge this in a few weeks
- finish the release process tweaks (almost there)
- enjoy our first release since a long time 🍻

Highlights are :
- reworked task-management system (see PBTask)
- finalized the separation of PBGitRepository from anything document-related.
- reworked the sheets API

So if developers/users want to give a hand in testing, please give this a spin !

@gitx/core @ksuther @mangerlahn @muhqu

### CODE REVIEW

**Comment by ksuther** [comment]
Thank you for all the updates!

I'm now running this with @mangerlahn's branch merged in (it merged cleanly other than stray xcodeproj and xib conflicts).

I'd suggest moving to the latest ObjectiveGit in this branch as well. The current version of ObjectiveGit/libgit2 that gitx is depending on is pretty old and has some problems that results in poor performance on repositories with lots of submodules (https://github.com/libgit2/libgit2/pull/4016).

**Comment by aharrison24** [comment]
I'm trying out the `develop` branch now. Just had it crash when I tried to perform a push from the UI. The push seems to have happened, but GitX crashed immediately after. Here's the error report:
https://gist.github.com/aharrison24/713ab5aac9f9eb5e6bfd1de2368d78ed

Key piece of info appears to be:
```
*** Terminating app due to uncaught exception 'WebKitThreadingException', reason: '-[WebView windowScriptObject] was called from a secondary thread'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by ksuther** [comment]
PBTask throws an exception when trying to discard changes to a file. It looks like NSPipe doesn't allow calling `offsetInFile` on its file handle.

```
*** -[NSConcreteFileHandle offsetInFile]: Illegal seek
(null)
```

```
* thread #32, queue = 'com.apple.NSFileHandle.fd_monitoring', stop reason = breakpoint 1.1
    frame #0: 0x00007fff7b35cc46 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x00007fff5474c9ed CoreFoundation`+[NSException raise:format:] + 205
    frame #2: 0x00007fff5679ecbf Foundation`-[NSConcreteFileHandle offsetInFile] + 78
  * frame #3: 0x00000001000f4291 GitX`__48-[PBTask performTaskOnQueue:terminationHandler:]_block_invoke.157(.block_descriptor=<unavailable>, handle=0x000060c0005f6d40) at PBTask.m:149
    frame #4: 0x00007fff5682af68 Foundation`__33-[NSConcreteFileHandle _monitor:]_block_invoke + 50
    frame #5: 0x000000010037a692 libclang_rt.asan_osx_dynamic.dylib`__wrap_dispatch_source_set_event_handler_block_invoke + 290
    frame #6: 0x00000001017f8d1f libdispatch.dylib`_dispatch_client_callout + 8
    frame #7: 0x000000010180d3c3 libdispatch.dylib`_dispatch_continuation_pop + 940
    frame #8: 0x00000001017fb41a libdispatch.dylib`_dispatch_source_invoke + 658
    frame #9: 0x000000010180e8c4 libdispatch.dylib`_dispatch_queue_serial_drain + 425
    frame #10: 0x0000000101800790 libdispatch.dylib`_dispatch_queue_invoke + 322
    frame #11: 0x000000010180ffbb libdispatch.dylib`_dispatch_root_queue_drain_deferred_wlh + 785
    frame #12: 0x0000000101814e94 libdispatch.dylib`_dispatch_workloop_worker_thread + 892
    frame #13: 0x000000010187502b libsystem_pthread.dylib`_pthread_wqthread + 980
    frame #14: 0x0000000101874c45 libsystem_pthread.dylib`start_wqthread + 13
```

**Comment by tiennou** [comment]
Heads-up ! Those two issues should be gone now (first 2 commits above). I've also reworked the error reporting so we get (hopefully) nicer error messages when tasks fail.

**Comment by ksuther** [comment]
Discard changes is working again. Another regression that I found: Commit hooks aren't working. I have a pre-commit and commit-msg hook and no warning appears anymore when they fail. I haven't had a chance to debug it myself yet.

**Pull request merged**
