### PR TITLE
Fix for arm64 runner

### PR DESCRIPTION
**Pull request by hannesa2**
master is broken on arm64 runner 
https://github.com/gitx/gitx/pull/391

### CODE REVIEW

**Comment by hannesa2** [comment]
I run into this on arm64 runner

image

**Comment by hannesa2** [comment]
Even in terminal the `--output` doesn't work anymore
image

**Comment by ADTC** [comment]
@hannesa2 It should be `--output=$PATH`. Notice the `=` (equal sign) instead of ` ` (space). You can see in [the man doc](https://www.unix.com/man-page/osx/1/base64/).

It's usually the case for `--` (double dash) options in Unix. I haven't seen an exception before. Surprised it worked before with the space.

**Comment by ADTC** [comment]
@hannesa2 BTW, shouldn't we fix this in `BuildRelease.yml` also?

**Comment by hannesa2** [comment]
> @hannesa2 BTW, shouldn't we fix this in `BuildRelease.yml` also?

sure !

**Pull request merged**
