### PR TITLE
Improve the build & installation instructions

### PR DESCRIPTION
**Pull request by ADTC**
Direct readers to the Releases page to get the pre-built release so they can use it immediately. Also update the information about building from source code.

### CODE REVIEW

**Review by hannesa2 — DISMISSED** [review]

**Comment by hannesa2** [comment]
What's going on there ?
image

**Comment by ADTC** [comment]
@hannesa2 I'm not sure. Since I only changed the `README` I don't suppose I caused it. I saw the other recent pull requests also have build failures.

It could be something related to the notarization in #334 and #339. @insha please help.

**Comment by ADTC** [comment]
@hannesa2 It looks like the workflows run from these PRs opened from forks with NEVER be able to access the secrets. **This is a GitHub limitation,** so they will ALWAYS fail no matter what. The only way to have passing workflows is for you to get the changes into a branch here and open a new PR here (not from a fork).

image

It is pretty ridiculous if you ask me. Anyway, my change is only on the README file. I'd like to see it merged.

**Comment by hannesa2** [comment]
Two weeks ago it was working properly, 
image

I've to investigate what's the new root cause here.

**Comment by hannesa2** [comment]
please rebase

**Review by hannesa2 — APPROVED** [review]

**Comment by ADTC** [comment]
@hannesa2 done. 1 workflow awaiting approval.

**Pull request merged**
