### PR TITLE
update the icon ✨

### PR DESCRIPTION
**Pull request by elia**
I took the new Terminal icon and replaced the contents with the classic white +/- in blue field.
The current icon is based on the old Terminal icon so I hope this change is less controversial than an icon change usually is 😉 

This is what the new icon looks like:

grab

And in context:

---

grab

---

screen shot 2017-01-27 at 13 58 25

_Misc files used to build the icon (just for reference): [gitx-icon.zip](https://github.com/gitx/gitx/files/736896/gitx-icon.zip)_

### CODE REVIEW

**Comment by nanotech** [comment]
Looks good! If we want to switch to this, I [remade this in JavaScript-parameterized SVG][2] ([source][1]) so we aren't using Apple resources, and also made pixel-aligned small versions:

icon_16x16 
icon_32x32 
icon_32x32 2x 
icon_128x128

These don't have the screen dot effect as that was the easier choice in SVG. I was also kind of worried about aliasing when the pattern is scaled.

[1]: https://github.com/nanotech/gitx/blob/f/new-icon/Resources/Images/gitx.html
[2]: https://rawgit.com/nanotech/gitx/1f451670fbc4e65e5898e34743091ce767ba6c26/Resources/Images/gitx.html

**Comment by ssp** [comment]
I don’t have a real opinion on the icon or expertise on creating great scaling behaviour … but whichever way this ends up, I think it would be a good idea to include the source files used to create the icon in the repository to make sure people don’t have to restart from scratch when the next colour change comes along.

**Comment by elia** [comment]
@nanotech I like the svg and I too did a try without the "pixel grid", I'm fine with whatever icon has the most consensus. The icon with the grid could certainly use some better pixel alignment but not having much time I just resized the Hi-res version. Also the current icon isn't much better (i.e. was made in the same way). 

The only other thing I have to say about the SVG version is that I have no idea on how to export it to `.icns`, if you know how to do that I think we can put those to the votes or just wait for an approval from above 😉.

---

@ssp I can definitely put the (rather low tech sources) in the repo. Just noticed there's already a `gitx_icon.psd` file inside `Resources/images` so I'll replace it with the updated one.

**Comment by nanotech** [comment]
@ssp gitx.html, gitx-16.svg and gitx-32.svg are the sources for my version and are included in [this commit][0]. I'll open a PR with that branch if we want to use it.

@elia Yeah, I was working off your gitx-0.png version. If you open gitx.html in a browser, clicking on the images will render them into a canvas and download them as PNGs. `rsvg-convert` from librsvg will also work, although I think it was darkening the gradient colors incorrectly on the smaller sizes. I set up Xcode to build the `.icns` from an asset catalog `.appiconset` of PNGs, or you could use `png2icns` or `iconutil` as usual.


[0]: https://github.com/nanotech/gitx/commit/1f451670fbc4e65e5898e34743091ce767ba6c26

**Comment by elia** [comment]
@ssp I was going to add the PSD but it's 8MB as is (with the two layers intact). 
If that's ok I'll add it as compressed which reduces the size to ~1MB.

**Comment by tiennou** [comment]
I like it @elia ! As I'm a complete noob w.r.t to the "true Xcode way" of managing assets, I'll let @nanotech handle whether it's preferable to have an xcasset file or a PSD one.

**Comment by nanotech** [comment]
@tiennou xcassets is just a folder of PNGs that Xcode will compile into an icns. It replaces a manually compiled icns, not PSD or SVG source files, so you would have both.

I've created a PR for my SVG version at #73.

**Pull request closed without merging**
