### PR TITLE
Carthage

### PR DESCRIPTION
**Pull request by ssp**
This PR tries to pick up on @rjmunro’s work in #217 to get dependencies with Carthage an make the project build with that.

To succeed in this, I had to use a non-master PR of the objective-git repo update the target macOS version, remove precompiled headers and add some explicit `#include`s to make that work.

I assume the code-signing area remains messed up as I have no idea what would even be a good state for that.

In addition the gitx command-line tool does not work in the current setup due to its dependency on the framework outside itself.

It this the way to go? Advice on how to proceed is welcome.

### CODE REVIEW

**Comment by jspiro** [comment]
Thanks for your contribution! I'm not qualified to advise here. Unless there's a plan to fix `gitx` CLI later, I wouldn't suggest merging this until there's a solution/plan. Also the CI will need to support it before it can be merged.

**Comment by rjmunro** [comment]
For the record, I didn't do the original work, it came from @pshirshov. I just made a PR from his branch.

**Comment by ssp** [comment]
Hey @rjmunro @jspiro 

I guess we have the same goal here. I’d really like to have a current version of GitX on my machine but have difficulties trying to build it. I am not even sure using Carthage is the right way to have the setup these days as I’m a bit out of the loop on building Mac software. And I agree we should have a fully functional app for that. Any idea on how to achieve that?

**Comment by hannesa2** [comment]
> I’d really like to have a current version of GitX on my machine but have difficulties trying to build it.

That's why I started to build any pull request on a CI. There you can look how to build successfully.
I'm not a pro to build mac software, but it's enough to build it. I tried to improve depended libraries as well, but some are dead projects or at least they ignore my pull request. This all makes it not easier. 
But in my point of view current way of dependencies is the right way.

But at least the current master will build properly #227 There you can see how to build local too

**Comment by jspiro** [comment]
Start by updating this PR so the checks build and pass. I am able to build GitX on my Mac, but I don't know anything about carthage, I'm not an XCode developer.

**Comment by hannesa2** [comment]
> I guess we have the same goal here. I’d really like to have a current version of GitX on my machine but have difficulties trying to build it.

@ssp 
Now it should work.

**Comment by hannesa2** [comment]
> Start by updating this PR so the checks build and pass. I am able to build GitX on my Mac, but I don't know anything about carthage, I'm not an XCode developer.

I'm with @jspiro I don't know the benefit of carthage and current way of git submodules is the way I love.
To be honest I would close it un-merged, or does someone comes with an other argument/idea ?

**Comment by tiennou** [comment]
I'm looking into it, as Carthage is the thing I used to cut releases of OCGit and I don't feel like changing that (`carthage archive` and put the archive manually into a release). Though I need the iOS build to work there and I'm not eager to have OpenSSL in my way (*Hello darkness…*).

@hannesa2 Is it fine with you if I cherry-pick stuff from your current OCGit master, knowing that it's likely it'll get completely out-of-sync afterward and will need either a merge, a rebase or a reset on top of that?

**Comment by tiennou** [comment]
> I don't know the benefit of carthage

It's mostly a package manager, as `apt` would be on Linux (though for libraries only). It saves you from having to build dependencies if there's a binary release available, and you can also switch it to "submodule mode" so you can keep submodules in the repository too. The only beef I have with it is that a lot has changed on the platform since it was picked up (`.xcframework`, Swift, Swift Package Manager, and now Apple Silicon) so I have to get up to speed on that too.

**Pull request closed without merging**
