### PR TITLE
Fix crash and miscellaneous cleanup

### PR DESCRIPTION
**Pull request by ksuther**
Fixes a crash introduced by bb8a5169c639a6bb148e58d421627516976f8ae5 and does some incremental cleanup that I performed while looking for the crash (remove unnecessary passing of PBGitRepository in arguments and removed instance variables marked with a FIXME).

### CODE REVIEW

**Review by jspiro — APPROVED** [review]

**Comment by jspiro** [comment]
I'm actually wondering why our CIA is not building. Do you think you could check the .github folder￼ and see if you can convince this to do a build with your changes?￼

**Review by jspiro — CHANGES_REQUESTED** [review]
Please try to get CI working on this build before we merge it.￼

**Comment by pioug** [comment]
I am just lurking here, but this may be helpful https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
image

**Comment by jspiro** [comment]
Aha! That's annoying. I guess it makes sense...ish. Lemme see what I can do.

**Review by jspiro — CHANGES_REQUESTED** [review]
There is a linker error.

**Comment by ksuther** [comment]
Fixed, thanks. Got a little too aggressive with committing Apple silicon support :)

**Review by jspiro — APPROVED** [review]

**Comment by jspiro** [comment]
Thank you for the contribution!

**Pull request merged**
