### PR TITLE
arm64 CI

### LINKED ISSUE #289: To build arm64 artifacts we need an Apple silicon custom runner
At least for release we will need it to sign the artifacts for `arm64`

e.g
* https://github.com/actions/runner/issues/805
* https://github.com/actions/runner/pull/1618 (**This is the most promising !**)
* https://github.com/mas-cli/m1-github-actions-runner
* https://gregmfoster.medium.com/using-m1-mac-minis-to-power-our-github-actions-ios-ci-540c55af13ea
* https://www.mirkogalimberti.com/post/2/github-actions-self-hosted-apple-silicon-m1-runner-howto

### PR DESCRIPTION
**Pull request by hannesa2**
closes #289 
It runs on a [custom runner v2.292.0](https://github.com/actions/runner/releases/tag/v2.292.0).  But it will not work always, because I've to turn it on manually and I've to enter my password for each job 

image

The next step is to wait for a public available M1 runner

### CODE REVIEW

**Comment by hannesa2** [comment]
There is an issue with the release job. It creates two of them and this causes an error

**Comment by hannesa2** [comment]
Please have a look on build times
image

**Comment by hannesa2** [comment]
It looks like this during pull request
image

But I'll remove arm64 build during pull request and keep it only during release, because it needs some manual steps https://github.com/gitx/gitx/pull/309#issue-1250335726

**Comment by niksy** [comment]
> The next step is to wait for a public available M1 runner

What about https://www.macstadium.com/opensource?

**Comment by hannesa2** [comment]
> > The next step is to wait for a public available M1 runner
> 
> What about https://www.macstadium.com/opensource?

Thanks a lot for the hint

image

**Pull request merged**
