### PR TITLE
Split view modernization, better window frame restoration and other fixes

### PR DESCRIPTION
**Pull request by ksuther**
Converted nibs with split views to Auto Layout and using split view autosave instead of managing it all by hand.
Auto Layout also gives us much cleaner resizing of split views.
One thing that was lost was the collapsable split view in the history view, but it can be reimplemented using the newer NSSplitView delegate methods much more easily in the future.

### CODE REVIEW

**Comment by ksuther** [comment]
Added better window frame saving as well. It would have caused merge conflicts to put them in a separate branch.

**Comment by tiennou** [comment]
I gave that a spin, and Xcode logged that :
```
[Layout] Detected missing constraints for <QLPreviewTitleBarView: 0x60e0000b1420>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.
```

Care to fix it ?

**Comment by ksuther** [comment]
That looks like it's coming from QuickLook, not our window or views. I'll see if I can get it to happen to make sure.

**Comment by ksuther** [comment]
Fixed the <QLPreviewTitleBarView logging and rebased off of master.

**Comment by ksuther** [comment]
Any chance of getting this and other PRs merged or commented on?

**Comment by tiennou** [comment]
Looks good, thanks !

**Pull request merged**
