### PR TITLE
Disable Address Sanitizer

### PR DESCRIPTION
**Pull request by ssp**
Doing this seems to undo the performance issues / high memory usage
recent builds had.

### CODE REVIEW

**Comment by nanotech** [comment]
Is turning ASan off for debug builds the right default? It does use more memory, but can help catch memory errors earlier, during development.

**Comment by tiennou** [comment]
Well, I like it when it's running. I'm not yet as proficient with it as with `leaks` though, but I prefer my memory smashers to be noisy 🤔.

Note that I found a few *oddities* in #61, which could cause the ASan "shadow" to always grow. This is only speculation though, but I don't know how well it reacts to a **lot** of objects created then immediately deleted. Eating 2GB would be my guess 😆.

**Comment by ssp** [comment]
@nanotech interesting question what a good default for this is. I tend to use debug builds on side projects like this one as I really want to use them to give the changes a realistic run but also have a debug build handy in case I discover an oddity that begs to be debugged.

My impression with this configuration was that it made GitX not workable (huge memory consumption, much slower) for my typical tasks.

Of course I can also switch to a release build / just as other people could turn on Address Sanitizer when required.

**Comment by tiennou** [comment]
https://gist.github.com/tiennou/a4d70d2687e31198497c80825441baac :wink:

**Pull request closed without merging**
