### PR TITLE
Update bundle version

### LINKED ISSUE #279: Sparkle is not working
Can anyone help to make Sparkle work properly ?

### PR DESCRIPTION
**Pull request by claytonrcarter**
May close #279

Sparkle checks versions by comparing the versions in the appcast vs the value of `CFBundleVersion` in `Info.plist`. In our case, `CFBundleIdentifier` is set to the number of commits in the repo, eg `2757`, but the Sparkle feed is using the semver tags (eg `0.17` or `0.18`). When Sparkle compares the app (bundle version) to the versions in the appcast, it will always think that the app is up to date because `2757 > 0.18`.

This changes the "post build" script (that updates the `CFBundleVersion`) to something like `0.18.2757`, so that Sparkle will compare something like `0.18.2757 > 0.17.2654` instead. This mimics how it used to be done (back when Sparkle was working). Look for the `sparkle:version` in [this old appcast.xml](https://s3.amazonaws.com/builds.phere.net/GitX/development/GitX-dev.xml) which were something like `0.15.1964`.

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Oh, BTW you can confirm this manually by manually editing the bundle version in `/Applications/GitX.app/Contents/Info.plist`. If you change it as follows, it will report that an update is available the next time you restart the app and check for updates:
```diff
    <key>CFBundleVersion</key>
-   <string>2757</string>
+   <string>0.16.2757</string>
```

Again, fingers crossed, but this *does* mean that the recent `0.17` and `0.18` versions will never auto-update. (Well, not until we tag a release for version > `2757.0.1` 😄). I believe that older versions (ie `0.15` and lower) *will* show an update ... but they will update to 0.18, and then not again for a while. 😄

**Comment by claytonrcarter** [comment]
This has passed and you can see the updated bundle version format in the build logs at  
```
BUILD VERSION: 0.18-13-g40c34c79
SHORT VERSION: 0.18
BUNDLE_VERSION: 0.18.2806
```

We will probably want to publish a new version (0.18.1?) soon, to pick up the new bundle version format. Again, 0.17 & 0.18 will not see this as an auto-update, but if they manually check for updates, it will at least show them a message like "there is a new version but you're up to date".)

**Comment by claytonrcarter** [comment]
I have merged this and tagged a new 0.18.1 release.

**Comment by hannesa2** [comment]
I manually fixed changelog and I will build a M1 artifact

**Pull request merged**
