### PR TITLE
Added support for opening submodules in tab instead of separate window

### PR DESCRIPTION
**Pull request by plan44**
...by option-double-clicking the submodule in the sidebar (works from macOS 10.13)

### CODE REVIEW

**Comment by mangerlahn** [comment]
I really like this idea! It makes sence to open submodules in tabs. This could even be the default..

I am not one of the projects owners and don’t want to act like one, but here are some thoughts:

_Context menu support_
Currently we only get this by double clicking, pressing alt while showing the context menu would be nice. Something like „Open submodule in tab“ as an alternate menu item.

_Animation on open_
When opening the new tab, we get the default document based app animation when opening a new window. It would be nice if the window was not closed for a split second.. I am not sure if this is possible..

_Default behavior_
This is more of a general question. What should be the default behavior when opening a submodule?
No matter what, the *other* way should be available through pressing option.

Again, I am not in charge here so don’t take my comment too seriously 😉

**Comment by plan44** [comment]
I agree that a context menu entry would be nice, and also about the not-so-nice animation right now.

However, I'm not experienced enough a Mac developer to do these things. I intentionally kept my PR small and isolated enough to remain mostly confident the patch will not break other things ;-)

Of course I'd like to see full tab vs windows support, not only for submodules. Also for "Open recent" it would be nice to just press option to open in a tab instead of a separate window. I often use groups of repos that are not necessarily submodules. It's just a bit over my head to actually implement all this myself...

**Comment by Timmmm** [comment]
There is a global OS-wide option for this. (I found it after getting annoyed with Sourcetree opening new windows.) It's in System Preferences -> Dock (obviously; Apple intuitiveness at work) -> Prefer tabs when opening documents -> Always.

It works ok but I still think individual apps should have this setting because it makes some non-native apps behave weirdly (e.g. in Eclipse-based apps dialogs now open as tabs - yes I know... Eclipse... but still).

**Comment by plan44** [comment]
@Timmmm very interesting - didn't know that. Did you find out what the "manually" setting does?

However I certainly can't switch that on globally only for the very specific case of opening submodules in GitX ;-)

So I still hope this PR eventually gets merged.

**Comment by tiennou** [comment]
Sorry for the long turn-around 😟. To be frank, I'm not sold on adding tabs to the UI, because I don't think they're worth the UI weight for the usability they bring (they'd have to grab two shortcuts to move between them *cough* ⌃⇥ *cough*, and I'd prefer those to go to back/forward).

<rantmode>
I've set macOS "Move focus to next window" (in System Preferences > Keyboard > Shortcuts > Keyboard) to something awfully useful : ⌘<, which is just right of the left shift key on a French AZERTY keyboard (and it automatically mapped ⌘⇧< to "previous window"). The only things it can't keyboard-access are minimized windows.

**Comment by plan44** [comment]
@tiennou thanks for the comments! I know, the opinion on the value of tabs varies a lot. But tabs are there already for any multi-document app at the macOS window manager level. It would take extra work to *suppress* them in Gitx.
The only goal of my PR was to enhance the workflow for those people who *do* use tabs (like me - definitely tabs are a huge improvement for my use cases!) a tiny bit. @mangerlahn had a few extra ideas which would put more focus on tabs - while I would not object those from my point of view as nice additions, I can survive well without ;-)
So I hold up my original PR which *only* changes the behaviour when option-doubleclicking a submodule in the sidebar *and nothing else*. For those that do use tabs, this improves gitx a lot, everone else will most likely not even notice it.

**Comment by tiennou** [comment]
As I said, I'm not that sold on tabs, and I feel like they should at least be part of a more expansive rework of the GUI, instead of just a quick fix for submodules (I'm not even sure what the responder chain looks like when tabs get enabled, and its current state is already concerning as it is).

There are things that I'd (personally) like to get polished before tackling UI-things — though I'm now looking at a not-uniformly-dark-GitX window, so we'll see 😒…

**Comment by Timmmm** [comment]
Yeah since GitX *does* have tabs already I think this would be worth merging.

**Pull request merged**
