### PR TITLE
Notarization

### PR DESCRIPTION
**Pull request by hannesa2**
Followed https://www.appcoda.com/distribute-macos-apps/

Any help is welcome to make it work  or to improve it

### CODE REVIEW

**Comment by hannesa2** [comment]
@insha unfortunately it's Invalid

image

**Comment by hannesa2** [comment]
Now I see what's wrong

```
{
  "logFormatVersion": 1,
  "jobId": "eb32e2f9-e5f0-4ea1-8f2d-b7aff6c36991",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "GitX.zip",
  "uploadDate": "2022-09-13T08:24:49.799Z",
  "sha256": "554dbb8234d0fbdb5045f1baa5d1c822cf8ae4bfe6d976737e247f399cea81e5",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/MacOS/GitX",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/MacOS/GitX",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app/Contents/MacOS/Updater",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app/Contents/MacOS/Updater",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GitX.zip/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    }
  ]
}
```

Any help from a professional is highly appreciated

**Comment by macronaut-yml** [comment]
> Now I see what's wrong
> <snipped>
> Any help from a professional is highly appreciated

Sorry first time with Apple's notary service... does that mean _everything_ that is included in the binary has to be signed by the _same_ developer ID? I thought Sparkle and the ObjectiveGit frameworks were (or should be) signed by their respective teams.

**Comment by insha** [comment]
All right so I am now looking at the notarizing macOS application for distribution. At minimum it requires the following:

1. Enable code-signing for all of the executables you distribute, and ensure that executables have valid code signatures
2. Enable the Hardened Runtime capability for your app and command line targets
3. Use a “Developer ID” application, kernel extension, system extension, or installer certificate for your code-signing signature
4. Include a secure timestamp with your code-signing signature (Xcode does is automatically; but for custom workflows see [here](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733))
5. Don’t include the com.apple.security.get-task-allow entitlement with the value set to any variation of true
6. Link against the macOS 10.9 or later SDK

All of the above (paraphrased) is from the Apple Documentation on [Notarizing macOS Software](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution).

Hopefully the last two items are non-issues and adding the hardened runtime entitlement is fairly straight forward.

In addition we will need a Developer ID certificate, an accompanying provisioning profile, and an App ID. All of these are required for notarizing the application for distribution outside of the App Store; at least that is my understanding from reading Apple's documentation on the matter.

All these hoops that one has to jump through to notarize an app; kind of makes me think Apple doesn't really want people doing this 😅

**Comment by hannesa2** [comment]
I did my first steps in signing, but I've no clue what to do with _Developer ID Signing_  (following https://developer.apple.com/forums/thread/128166)

`If you’re distributing outside of the Mac App Store, use your Developer ID Application signing identity in place of III in the example above. This will typically be named Developer ID Application: TTT, where TTT identifies your team.`

I tried 

          DID="Developer ID Application: ${{ secrets.APPLE_TEAM_ID }}"

but using the secret here doesn't work.
This is the result
image


@insha Maybe we need an additional variable here, which prevent to have `***`  ? Maybe you can add it please ?

**Comment by insha** [comment]
> I did my first steps in signing, but I've no clue what to do with _Developer ID Signing_ (following https://developer.apple.com/forums/thread/128166)
> 
> `If you’re distributing outside of the Mac App Store, use your Developer ID Application signing identity in place of III in the example above. This will typically be named Developer ID Application: TTT, where TTT identifies your team.`
> 
> I tried
> ```
>       DID="Developer ID Application: ${{ secrets.APPLE_TEAM_ID }}"
> ```
> but using the secret here doesn't work. This is the result ...
> 
> @insha Maybe we need an additional variable here, which prevent to have `***` ? Maybe you can add it please ?

I don't think you need remove any of the signatures from any other framework that is included, it can remain as is. In my experiment, I only modified the GitX targets and didn't touch any of the included frameworks.

I can add another variable or two, however, my findings on this whole notarization is that in order to notarize an app, in addition to my credentials, the machine will need:
1. A certificate
2. A provisioning profile

The Provisioning Profile is dependent upon the **Certificate** and the **App ID.** I can create the Certificate; but when I go to create the Provisioning Profile, I am asked for an App ID. 

The _App ID_ is really the key here. An App ID is basically the bundle identifier and whatever capabilities that are needed for that particular app (in this instance none, except the Hardened Runtime).

The problem is, I _can't_ create the App ID for GitX using the `net.phere.GitX` bundle identifier, because it is not available for me to register with the App ID that I am creating. If I use my own, bundle identifier, e.g. `com.themacronaut.GitX`, I am able to create the App ID and then also the Provisioning Profile.

If a change to the bundle identifier is acceptable, then I can create a certificate, provisioning profile, and an App ID; where the App ID would use the new bundle identifier, `com.themacronaut.net.phere.GitX`, and then provide these to be added to the CI pipeline in order to use them for notarizing the app.

**Comment by hannesa2** [comment]
> I don't think you need remove any of the signatures

Sure, but this is not the issue.

I guess a more efficient way to implement this, is to test first necessary steps local and then apply it to pull request.
Sadly, I can't test it, because I don't have necessary secrets.

Feel free to add commits to this pull request, (make an own pull request which targets to this branche or to master)

**Comment by hannesa2** [comment]
> If this is fine, then I will move forward with it.

Yes, please move forward with all necessary steps 👍

**Pull request closed without merging**
