### PR TITLE
Change Travis to Xcode 8.3

### PR DESCRIPTION
**Pull request by ksuther**
It was trying to build with Xcode 7.1, which no longer exists on Travis.

### CODE REVIEW

**Comment by tiennou** [comment]
Well, it looks like we're testing `echo` 😆. Not sure since when it's not building though.

**Comment by ksuther** [comment]
The scheme wasn't defined in the config. That config hadn't been changed in a long time :)

**Comment by tiennou** [comment]
Oh I didn't realize you were still on it. I just made a branch with some outstanding changes I made a while ago, hoping those would work. I'll rebase on this one then. Thanks for the fix !

**Comment by ksuther** [comment]
Sorry, it takes a bit for Travis to spin up so I was waiting on it.

Thanks for getting gitx a new home. It's nice to see it being kept alive!

**Pull request merged**
