### PR TITLE
Fix the local build in Xcode

### PR DESCRIPTION
**Pull request by ADTC**
* ~Enable Xcode to automatically manage signing.~ _This is removed._
* Create a `GitX.xcconfig` file and set it as config for the GitX target.
* Add instructions to create a `Dev.xcconfig` file.
* Add this file in `.gitignore`.
* Add instructions to find Development Team ID and certificate name.

Fixes #366

### CODE REVIEW

**Comment by ADTC** [comment]
Right, so this won't work for the CI because it's looking for the Team ID which isn't present. Hmm...

**Comment by ADTC** [comment]
@hannesa2 please help me cancel the old `arm64` job so the new queued one can proceed. Thanks.

**Comment by ADTC** [comment]
@hannesa2 please help me cancel the old queued and running `arm64` jobs so that only the latest queued one here needs to run. Thanks.

**Comment by ADTC** [comment]
@jspiro oh I meant the older ones here: https://github.com/gitx/gitx/actions

Can you cancel those?

**Comment by ADTC** [comment]
Also the running one. It got stuck:
image

**Comment by jspiro** [comment]
> Also the running one. It got stuck:
> 
> image
> 
> 

It's failing to cancel. Push a commit to kick a new build.

**Comment by ADTC** [comment]
OK, thanks.

**Comment by jspiro** [comment]
git commit --allow-empty -m kick

**Comment by jspiro** [comment]
Cleaned all the builds up. Good to go now.

**Comment by ADTC** [comment]
@jspiro Done. I did a rebase and fixed up some commits. BTW, for `arm64` I think @hannesa2 needs to boot up the runner manually in MacStadium. Until then, it will be queued. Please don't cancel it.

**Review by hannesa2 — APPROVED** [review]

**Comment by hannesa2** [comment]
Concerning the arm runner: Yes, weeks ago it was removed from this repository, so I added it again.
But i[nstalling as service](https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service#installing-the-service) runs into an issue.
image

**Comment by ADTC** [comment]
@hannesa2 Thanks for the merge. I think this will help newcomers get started easily without having to muck up the tracked project files with their private info.

Regarding the runner, the instructions says you should use `sudo` and in my experience, services will refuse to start if you don't start them with `sudo`. Please try that. If you want to install with your user instead of `sudo`, I think it should be `./svc.sh install hannes`.

Failing the above, can you check if the service is disabled under Allow in the Background? (It's in System Settings/Preferences). Last attempt, try adding the application to Login Items. (You can choose the Shell Script there.)

**Comment by hannesa2** [comment]
Sure, this was my first idea
image

image

I wrote the support of github action a question  ...

**Comment by ADTC** [comment]
I cannot see your ticket. Support tickets are private in GitHub.

Try to uninstall the existing installation first, before installing with the username.
```
./svc.sh stop
./svc.sh uninstall
./svc.sh install hannes
./svc.sh start
```

**Comment by hannesa2** [comment]
Ok, I did it again
image

but still the same error

**Comment by hannesa2** [comment]
I opened a public discussion https://github.com/orgs/community/discussions/48686

**Comment by ADTC** [comment]
Is it still the same if you restart the Mac? Try the same steps again after a reboot.

**Comment by hannesa2** [comment]
A reboot doesn't help

**Comment by hannesa2** [comment]
I already tried all this low hanging fruits, but till now without success. 
I guess, I've to understand the root cause to be able to fix it.

**Comment by hannesa2** [comment]
@ADTC Just for the records, after chatting over days with github support, this is the workaround https://github.com/actions/runner/issues/1056#issuecomment-1201904324 which made the github-runner start during reboot.
It simply needs a logged user via GUI

**Pull request merged**
