### PR TITLE
Fixed "Show whitespace differences"

### LINKED ISSUE #267: "Show whitespace differences" check in Preferences doesn't work.
Whitespace Diff is always ON.

### PR DESCRIPTION
**Pull request by vng**
Closes #267

### CODE REVIEW

**Comment by hannesa2** [comment]
May I ask you to show a sample/screenshot to easier understand what it solves ?

**Comment by hannesa2** [comment]
Best would have a switch in preferences to be able to toggle, but I'm fine like it is 👍
Thanks a lot !

**Comment by vng** [comment]
Hm, but "Show whitespace differences" check in preferences is already about that, or you mean something else?
I just fixed that to work properly.

**Comment by hannesa2** [comment]
Really ? I didn't found it. Where ?

image

**Comment by vng** [comment]
:) You have "Integration" tab active. Current Preferences view looks ugly, see my issue a year ago https://github.com/gitx/gitx/issues/219

Screenshot 2022-02-15 at 15 01 18

Press on General button. General/Integration/Updates should be the buttons on a toolbar, like it was 2 years ago .. Seems like MacOS 11 SDK broke it, I'm not a professional in UI development.

**Comment by vng** [comment]
This is how it was 2 years ago and should look like:
Screenshot 2022-02-15 at 15 05 09

**Comment by hannesa2** [comment]
2 years ago it was much better !
Now you have to push this button, to see settings. 

image

Without your help, I would never find it. Ok, there is no need for it, but anyway !

**Comment by vng** [comment]
> If you need a new version, please let me know

@hannesa2 Should we set ONLY_ACTIVE_ARCH = YES; in Debug and Release for MGScopeBar, ObjectiveGit and Sparkle frameworks like its set in main GitX project?

I tried to build Release and failed because I don't have arm64 libgit2, libssh2 to link into ObjectiveGit.

**Comment by hannesa2** [comment]
Please make a pull request, and I'll try it out on my `am64` side.

Just for the records, these are the current settings 
image

**Comment by hannesa2** [comment]
> I tried to build Release and failed because I don't have arm64 libgit2, libssh2 to link into ObjectiveGit.

But at least the `x86_64` build should work on your side

**Comment by vng** [comment]
ObjectiveGit has ONLY_ACTIVE_ARCH = YES only in Debug, so my x64 machine tries to build arm64 ObjectiveGit in Release and fails.

Please, try it by yourself, because I should change submodules, but I'm unable to push into them. Making forks of all submodules is a mess :)

**Comment by hannesa2** [comment]
For `External/Sparkle` we use no fork. Makes this all sense without `Sparkle` ?
I want to avoid to create a new fork of `Sparkle` just because of this single switch

**Comment by vng** [comment]
I think ObjectiveGit will be enough

**Comment by hannesa2** [comment]
Here you go
* https://github.com/gitx/MGScopeBar/pull/16
* https://github.com/gitx/objective-git/pull/46
* https://github.com/gitx/gitx/pull/283

**Pull request merged**
