### PR TITLE
Generate appcast.xml

### PR DESCRIPTION
**Pull request by claytonrcarter**
See https://github.com/gitx/gitx/issues/279#issuecomment-1041925791

This is my last, best hope. It adds a `docs` dir w/ 1 file. To work, we will also need to:

1. In repo settings, go to "Pages"
2. Change "Source" from "None" to `master`
3. Change "/ (root)" to `/docs`

This *should* tell GH to build the `docs` dir on any update to `master` and publish it to `https://gitx.github.io/gitx`. In this case, it will only include the `appcast.xml` file, which happens to be exactly where GitX is already looking for the appcast file: https://github.com/gitx/gitx/blob/master/Resources/Info.plist#L97

If all goes well, this site/file will be rebuilt on any push to `master`, but there may be a way to trigger it to rebuild only when tags are pushed (ie a release is made). I have not looked in to this.

Also, we should probably remove the `origin/gh-pages` branch b/c it is a) out of date and b) misleading. For example, if you got to `https://gitx.github.io` you'll see the code/site from the `gitx/gitx.github.io` repo, but if you go to `https://gitx.github.io/gitx` you'll see the code from this repo's `gh-pages` branch. I don't think that this is controversial, but it does mean that `https://gitx.github.io/gitx/index.html` will stop working.

### CODE REVIEW

**Comment by claytonrcarter** [comment]
FYI, here's more info on configuring the "build source" for the page: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

Also, there are different types of GH pages, more info here: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites

The idea is that `gitx.github.io` is an org page, but we can also configure this repo to have a project page. The org page would be at `https://<org>.github.io` while the project page is at `https://<org>.github.io/<project>`

There's some add'l info about the publishing sources (branches/directories, etc) here https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites

**Comment by claytonrcarter** [comment]
> Puhhh, you become a Sparkle professional !

Ha! I'm not so sure about that... 

>  You wrote about trigger on push to master: Not a github action, right ? But what triggers it ?

Honestly, I don't know, but I think that it's just how GH pages work. Eg there's no gh action on the `gitx.github.io` repo but it still works via GH actions: https://github.com/gitx/gitx.github.io/actions. I believe that the the same is true for `gh-pages` branch.

> Anyway, when this is merges and all is working: all is fine, then we ca drop gh-pages branch. Right ?

Yes, that's my understanding. If this is merged, we will lose https://gitx.github.io/gitx/index.html, but like I said, that's already outdated and "unmaintained" in favor of `gitx.github.com`. If that's a concern, we could probably put a stub HTML page there directing folks to the new/real site.

**Comment by claytonrcarter** [comment]
> has the touch of over-engineering

Ugh, yes. It would be great if Sparkle could just point to a GH releases feed and do the work itself, but the issue I found suggested that they weren't interested.

**Comment by hannesa2** [comment]
Keep finger crossed ....

**Comment by claytonrcarter** [comment]
Hmm, nothing yet ... ?? Did you update the Pages settings in the repo Settings? (I can't.)

I also see that the `github-pages` env wasn't triggered ... which means 🤷 to me: https://github.com/gitx/gitx/deployments/activity_log?environment=github-pages

Maybe back to the drawing board...?

**Comment by claytonrcarter** [comment]
After setting the pages settings as described in the PR description, this worked in my fork (FWIW): https://claytonrcarter.github.io/gitx/appcast.xml (there are no releases in that fork, so nothing in that file, but it built and is published)

**Comment by hannesa2** [comment]
> Did you update the Pages settings in the repo Settings? (I can't.)

Now you can do it

**Comment by claytonrcarter** [comment]
Thank you for the invite! Unfortunately, this doesn't give me access to the repo Settings. (I at least, I don't see that it does.)

BUT IT DOES give me access to push to branches, so I just pushed these same changes to the `gh-pages` branch ... and it worked! https://gitx.github.io/gitx/appcast.xml

Screen Shot 2022-02-16 at 7 19 33 PM

BUT clearly there is something up w/ the Sparkle file b/c it's not comparing the versions correctly. 😕

**Comment by hannesa2** [comment]
Does it still needs some changes ?
image

**Comment by hannesa2** [comment]
> Unfortunately, this doesn't give me access to the repo Settings.

I see your access was `write`, I changed to `admin`.

The issue is, I can't add you to group `Core` I guess this permission is missing on my side.
image

So, I solved it by giving you this interim solution to add you directly to repo. This it just _temporary_.
In general, interim solution are mostly for ever 😉

**Comment by claytonrcarter** [comment]
Thank you. That did the trick:

Screen Shot 2022-02-17 at 7 20 58 AM

So (if this works), then any push to `master` will rebuild the appcast.xml file.

**Comment by hannesa2** [comment]
Hi @claytonrcarter as I'm complete out of scope of this appcast thing, and I got a feedback https://github.com/Homebrew/homebrew-cask/pull/250530#issuecomment-3939115257 on homebrew, I ask you, how to solve this ?

**Comment by hannesa2** [comment]
How to move here to 1.2 as well ? 
image
As I don't know how it is generated, I'm complete out of ideas

**Pull request merged**
