### PR TITLE
Align commit view elements

### PR DESCRIPTION
**Pull request by elia**
### Before:

screen shot 2018-04-11 at 18 48 26

---

### After:

screen shot 2018-04-11 at 18 54 03

screen shot 2018-04-11 at 18 54 37

### CODE REVIEW

**Comment by goneng** [comment]
Nice!
A bit confusing for me, in terms of UI conventions.
How about you move the "Amend" and [Commit] items
to the mid area, near the "Commit Message" and "Staged Changes" headers?
(Can put the "Amend" to the right of the "Commit Message" header
and the [Commit] button to the right of the "Staged Changes", for example)

**Comment by elia** [comment]
I don't know much about macOS UI conventions, but putting the button before the text area doesn't look right to me.

**Comment by mangerlahn** [comment]
I like that the three text views have the same hight now! However, I am not sure if floating buttons inside scrollViews are that common on macOS. The only thing that comes to mind is Apple Maps. But technically, thats not even a scroll view ;)

I am also not an UI expert, but I began drafting an slightly new UI for GitX under #91. A lot of the controls have moved to the toolbar there. 

Now, there is the big difference between the staging and the git history view. 
So, all the buttons relevant to the history view would either be disabled or hidden in the staging view. I feel like the former is the more recommended way to do, but the latter would allow these buttons to appear in the toolbar instead of the content. I am not sure if the disconnect between buttons and content is too big though.

While writing this, another idea came to my mind. What about making the staging view a modal sheet on top of the history list?
Thats basically how it works in Xcode. Then these buttons would have their own row at the bottom. State is always persisted and one could switch between staging and history list with one key command (like before). I am very open to thoughts on this!

**Comment by elia** [comment]
This is just the adjustments I had locally because I didn't like the previous layout. I'd be fine to have this merged and then overwritten by anything better by someone more expert than me 😄 🎨 🖌 

I also tried (that was some time ago) a couple combinations with the button outside the scrollable view, both above and below, none of them looked right. This was pleasurable and worked well for some months 👍

**Comment by tiennou** [comment]
I'm definitely 👎 on the "hovering buttons" (sorry for the letdown), but I had some thoughts looking at the screenshots.

I think I'd merge the Stage/Unstage table view, because now that I look at it, it's a *real* pain to use with a mouse (I think there were arrow-keys keyboard shortcuts, but I always forget them (checking) aaaand they don't actually work anymore 😭).

Maybe some kind of 3 column-tableview (so stage/unstage are closer, but this obviously needs more UX thinking), which allows moving the commit message view to either the left or right of that table (I'd say to the right, because I usually stage things before I know what I'm actually commiting), with the "commit action things" below, which makes the (mis)alignment less visible.

**Comment by goneng** [comment]
tiennou, I'm with you -
switch the "Staged Changes" column with the "Commit Message" column,
and move the checkbox and button to the right (above or below the text-areas).

**Comment by elia** [comment]
I've moved the controls outside the commit box basically just fixing misalignments

screen shot 2018-04-14 at 08 52 23

**Comment by tiennou** [comment]
Thanks @elia for fixing this !

**Pull request merged**
